
#ifdef MHYPER
#ifdef _TABLE
PUBLIC vm_drivers_t  dflt_driver[NR_DFT_DRIVERS] = {
/* process name,  type */ 
 { "idle",  	DISABLED_PROC_TYPE | BOOT_LOADED | KERNEL_LEVEL  | DONOT_NTFY },
 { "clock",		DISABLED_PROC_TYPE | BOOT_LOADED | KERNEL_LEVEL | DONOT_NTFY },
 { "system",	VIRTUAL_PROC_TYPE  | BOOT_LOADED | KERNEL_LEVEL | DONOT_NTFY }, 
/* { "system",	DISABLED_PROC_TYPE  | BOOT_LOADED | KERNEL_LEVEL | DONOT_NTFY }, */
 { "kernel",	DISABLED_PROC_TYPE | BOOT_LOADED | KERNEL_LEVEL | DONOT_NTFY },
 
 { "pm"    ,	REAL_PROC_TYPE | BOOT_LOADED | SERVER_LEVEL | DONOT_NTFY },
 { "fs"    ,	REAL_PROC_TYPE | BOOT_LOADED | SERVER_LEVEL | DONOT_NTFY },
 { "rs"    ,	REAL_PROC_TYPE | BOOT_LOADED | SERVER_LEVEL | DONOT_NTFY },
 { "ds"    ,	REAL_PROC_TYPE | BOOT_LOADED | SERVER_LEVEL | DONOT_NTFY },

 { "tty"   ,	PROMISCUOUS_PROC_TYPE | BOOT_LOADED | TASK_LEVEL | BOOT_NTFY },
 { "mem"   ,	REAL_PROC_TYPE | BOOT_LOADED | TASK_LEVEL | DONOT_NTFY },
 { "log"   ,	REAL_PROC_TYPE | BOOT_LOADED | TASK_LEVEL | DONOT_NTFY },
 { "vmm"   ,	DISABLED_PROC_TYPE | BOOT_LOADED | SERVER_LEVEL | DONOT_NTFY },
 
 { "init"  ,	REAL_PROC_TYPE | BOOT_LOADED | USER_LEVEL | DONOT_NTFY },
 { "floppy"  ,	VIRTUAL_PROC_TYPE | EXEC_LOADED | TASK_LEVEL | DONOT_NTFY },					
 { "is"  ,		PROMISCUOUS_PROC_TYPE | EXEC_LOADED | SERVER_LEVEL | DONOT_NTFY },
 { "at_wini"  ,	PROMISCUOUS_PROC_TYPE | EXEC_LOADED | TASK_LEVEL | EXEC_NTFY },
 
 { "pci"  ,		PROMISCUOUS_PROC_TYPE  | EXEC_LOADED | TASK_LEVEL | DONOT_NTFY },
 { "printer"   ,REAL_PROC_TYPE | EXEC_LOADED | TASK_LEVEL | DONOT_NTFY | PARAVIRTUAL },
 { "cmos"   ,	PROMISCUOUS_PROC_TYPE  | EXEC_LOADED | TASK_LEVEL | DONOT_NTFY },
  { "random"   ,PROMISCUOUS_PROC_TYPE  | EXEC_LOADED | TASK_LEVEL | DONOT_NTFY },

   { "lance"   , DISABLED_PROC_TYPE  | EXEC_LOADED | TASK_LEVEL | DONOT_NTFY },
 { "inet"   ,	DISABLED_PROC_TYPE  | EXEC_LOADED | SERVER_LEVEL | DONOT_NTFY },

};

#else /* _TABLE */
extern vm_drivers_t  dflt_driver[NR_DFT_DRIVERS];
#endif /* _TABLE */

#endif /* MHYPER */
